import { jsPDF } from "jspdf";
import { sanitizeInvoiceItems } from "./invoiceUtils";
import { INVOICEHUB_LOGO_PNG } from "./invoiceHubLogo";

function formatMoney(amount) {
  return `N${Number(amount || 0).toLocaleString()}`;
}

function formatDate(value = new Date()) {
  const date = new Date(value || new Date());

  if (Number.isNaN(date.getTime())) {
    return new Date().toLocaleString();
  }

  return date.toLocaleDateString();
}

function cleanFilePart(value) {
  return String(value || "invoice")
    .replace(/[^a-z0-9_-]+/gi, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

function maybeText(doc, text, x, y, options = {}) {
  const wrapped = doc.splitTextToSize(String(text || ""), options.maxWidth || 460);
  doc.text(wrapped, x, y, { align: options.align || "left" });
  return wrapped.length * 14;
}

export function buildInvoicePdf({ invoice = {}, owner = {}, origin = "" } = {}) {
  const customerName =
    invoice.customer || invoice.customerName || invoice.student || "Customer";
  const businessName = invoice.businessName || owner.businessName || "InvoiceHub";
  const invoiceNumber = invoice.invoiceNumber || "Pending";
  const invoiceDate = invoice.date || invoice.createdAt || new Date();
  const dueDate = invoice.dueDate || invoice.date || invoice.createdAt || new Date();
  const description =
    invoice.description || invoice.category || invoice.class || "Invoice payment";
  const items = sanitizeInvoiceItems(invoice.items || []);
  const totalAmount = Number(invoice.amount || invoice.total || invoice.subtotal || 0);
  const paymentLink = origin && invoice.token ? `${origin.replace(/\/$/, "")}/pay/${invoice.token}` : "";

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = 78;

  doc.addImage(INVOICEHUB_LOGO_PNG, "PNG", margin, 22, 24, 28);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("InvoiceHub", margin + 32, 41);

  doc.setFontSize(24);
  doc.text(businessName, margin, y);
  doc.setFontSize(14);
  doc.text("Invoice", pageWidth - margin, y, { align: "right" });
  y += 32;

  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(1);
  doc.line(margin, y, pageWidth - margin, y);
  y += 28;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Invoice Number: ${invoiceNumber}`, margin, y);
  doc.text(`Invoice Date: ${formatDate(invoiceDate)}`, pageWidth - margin, y, { align: "right" });
  y += 18;
  doc.text(`Due Date: ${formatDate(dueDate)}`, margin, y);
  doc.text(`Customer: ${customerName}`, pageWidth - margin, y, { align: "right" });
  y += 28;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Description", margin, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  y += maybeText(doc, description, margin, y, { maxWidth: pageWidth - margin * 2 });
  y += 12;

  if (items.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Items", margin, y);
    y += 18;

    items.forEach((item, index) => {
      if (y > doc.internal.pageSize.getHeight() - 120) {
        doc.addPage();
        y = 56;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(`${index + 1}. ${item.description}`, margin, y);
      y += 14;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.text(`Quantity: ${item.quantity}   Unit Price: ${formatMoney(item.unitPrice)}`, margin, y);
      doc.text(`Line Total: ${formatMoney(item.lineTotal)}`, pageWidth - margin, y, { align: "right" });
      y += 18;
    });

    y += 8;
  }

  if (y > doc.internal.pageSize.getHeight() - 160) {
    doc.addPage();
    y = 56;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Total", margin, y);
  doc.text(formatMoney(totalAmount), pageWidth - margin, y, { align: "right" });
  y += 28;

  if (paymentLink) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Payment Link", margin, y);
    y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    y += maybeText(doc, paymentLink, margin, y, { maxWidth: pageWidth - margin * 2 });
    y += 12;
  }

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(
    "This invoice was generated by InvoiceHub.",
    margin,
    doc.internal.pageSize.getHeight() - 40
  );

  return Buffer.from(doc.output("arraybuffer"));
}

export function buildInvoiceAttachment({ invoice = {}, owner = {}, origin = "" } = {}) {
  const buffer = buildInvoicePdf({ invoice, owner, origin });
  const invoiceNumber = cleanFilePart(invoice.invoiceNumber || invoice._id || "invoice");

  return {
    filename: `invoice-${invoiceNumber}.pdf`,
    mimetype: "application/pdf",
    base64: buffer.toString("base64"),
    size: buffer.length,
  };
}
