import { jsPDF } from "jspdf";
import { sanitizeInvoiceItems } from "./invoiceUtils";
import { INVOICEHUB_LOGO_PNG } from "./invoiceHubLogo";

function formatMoney(amount) {
  return `N${Number(amount || 0).toLocaleString("en-NG", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  })}`;
}

function formatDate(value = new Date()) {
  const date = new Date(value || new Date());

  if (Number.isNaN(date.getTime())) {
    return new Date().toLocaleDateString("en-NG");
  }

  return date.toLocaleDateString("en-NG", {
    year: "numeric",
    month: "short",
    day: "2-digit",
  });
}

function cleanFilePart(value) {
  return String(value || "invoice")
    .replace(/[^a-z0-9_-]+/gi, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

function getOriginalInvoiceAmount(invoice = {}) {
  const amount = Number(
    invoice.originalAmount ?? invoice.amount ?? invoice.total ?? invoice.subtotal ?? 0
  );

  return Number.isFinite(amount) ? Math.max(amount, 0) : 0;
}

function getAmountPaid(invoice = {}) {
  const paidAmount = Number(invoice.paidAmount ?? invoice.amountPaid ?? 0);

  return Number.isFinite(paidAmount) ? Math.max(paidAmount, 0) : 0;
}

function getAmountDue(invoice = {}) {
  const status = String(invoice.status || invoice.paymentStatus || "").toLowerCase();

  if (status === "paid") {
    return 0;
  }

  const originalAmount = getOriginalInvoiceAmount(invoice);
  const paidAmount = getAmountPaid(invoice);
  const balanceDue = Number(invoice.balanceDue ?? invoice.balance);

  if (Number.isFinite(balanceDue) && balanceDue > 0) {
    return Math.min(balanceDue, originalAmount || balanceDue);
  }

  if (paidAmount > 0) {
    return Math.max(originalAmount - paidAmount, 0);
  }

  return originalAmount;
}

function setText(
  doc,
  {
    font = "helvetica",
    style = "normal",
    size = 10,
    color = [15, 23, 42],
  } = {}
) {
  doc.setFont(font, style);
  doc.setFontSize(size);
  doc.setTextColor(...color);
}

function addCard(doc, x, y, width, height, options = {}) {
  const {
    fill = [248, 250, 252],
    stroke = [226, 232, 240],
    radius = 10,
  } = options;

  doc.setFillColor(...fill);
  doc.setDrawColor(...stroke);
  doc.setLineWidth(0.7);
  doc.roundedRect(x, y, width, height, radius, radius, "FD");
}

function splitText(doc, text, width) {
  return doc.splitTextToSize(String(text || "-"), width);
}

function truncateText(value, maxLength = 80) {
  const text = String(value || "-").trim();

  if (text.length <= maxLength) {
    return text;
  }

  return `${text.slice(0, maxLength - 3)}...`;
}

function drawDocumentHeader({
  doc,
  businessName,
  documentTitle = "Invoice",
  margin,
  pageWidth,
  startY = 30,
}) {
  let y = startY;

  doc.addImage(INVOICEHUB_LOGO_PNG, "PNG", margin, y - 8, 24, 28);

  setText(doc, {
    font: "helvetica",
    style: "bold",
    size: 11,
    color: [15, 23, 42],
  });

  doc.text("InvoiceHub", margin + 32, y + 10);

  setText(doc, {
    font: "helvetica",
    style: "normal",
    size: 8,
    color: [100, 116, 139],
  });

  doc.text("Generated invoice", pageWidth - margin, y + 10, {
    align: "right",
  });

  y += 48;

  const documentTitleText = String(documentTitle || "Invoice").toUpperCase();
  const badgeWidth = 84;
  const badgeHeight = 24;
  const badgeX = pageWidth - margin - badgeWidth;
  const badgeY = y - 20;

  doc.setFillColor(241, 245, 249);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.7);
  doc.roundedRect(badgeX, badgeY, badgeWidth, badgeHeight, 12, 12, "FD");

  setText(doc, {
    font: "helvetica",
    style: "bold",
    size: 8,
    color: [71, 85, 105],
  });

  doc.text(documentTitleText, badgeX + badgeWidth / 2, badgeY + 16, {
    align: "center",
  });

  const businessMaxWidth = pageWidth - margin * 2 - badgeWidth - 24;

  setText(doc, {
    font: "helvetica",
    style: "bold",
    size: 17,
    color: [15, 23, 42],
  });

  const businessLines = doc.splitTextToSize(
    String(businessName || "Business").trim(),
    businessMaxWidth
  );

  const maxBusinessLines = businessLines.slice(0, 2);
  doc.text(maxBusinessLines, margin, y);

  y += maxBusinessLines.length * 20;

  setText(doc, {
    font: "helvetica",
    style: "normal",
    size: 8.5,
    color: [71, 85, 105],
  });

  doc.text("Invoice generated by InvoiceHub.", margin, y + 5);

  y += 24;

  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageWidth - margin, y);

  return y + 18;
}

function addLabelValue(doc, label, value, x, y, width) {
  setText(doc, {
    font: "helvetica",
    style: "bold",
    size: 7.8,
    color: [100, 116, 139],
  });

  doc.text(String(label || "").toUpperCase(), x, y);

  setText(doc, {
    font: "helvetica",
    style: "normal",
    size: 9.3,
    color: [15, 23, 42],
  });

  const lines = splitText(doc, value || "-", width);

  doc.text(lines.slice(0, 2), x, y + 13);

  return y + 34;
}

function drawFooter(doc, { margin, pageWidth, footerY }) {
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, footerY - 15, pageWidth - margin, footerY - 15);

  setText(doc, {
    font: "helvetica",
    style: "normal",
    size: 8,
    color: [100, 116, 139],
  });

  doc.text("Generated by InvoiceHub", margin, footerY);

  doc.text("This invoice was generated electronically.", pageWidth - margin, footerY, {
    align: "right",
  });
}

function drawItemsTable({
  doc,
  items,
  x,
  y,
  width,
  maxHeight,
}) {
  const headerHeight = 22;
  const rowHeight = 28;
  const footerNoticeHeight = 16;
  const descriptionWidth = width - 220;
  const qtyX = x + descriptionWidth + 18;
  const unitPriceX = qtyX + 46;
  const totalX = x + width;

  const maxRows = Math.max(
    1,
    Math.floor((maxHeight - headerHeight - footerNoticeHeight) / rowHeight)
  );

  const visibleItems = items.slice(0, maxRows);
  const hiddenCount = Math.max(items.length - visibleItems.length, 0);

  doc.setFillColor(241, 245, 249);
  doc.roundedRect(x, y, width, headerHeight, 8, 8, "F");

  setText(doc, {
    font: "helvetica",
    style: "bold",
    size: 7.8,
    color: [71, 85, 105],
  });

  doc.text("DESCRIPTION", x + 10, y + 15);
  doc.text("QTY", qtyX, y + 15);
  doc.text("UNIT", unitPriceX, y + 15);
  doc.text("TOTAL", totalX, y + 15, {
    align: "right",
  });

  y += headerHeight + 7;

  visibleItems.forEach((item, index) => {
    const rowY = y + index * rowHeight;
    const descriptionText = truncateText(
      item.description || `Item ${index + 1}`,
      58
    );

    setText(doc, {
      font: "helvetica",
      style: "normal",
      size: 8.8,
      color: [15, 23, 42],
    });

    doc.text(descriptionText, x + 10, rowY + 11);

    setText(doc, {
      font: "helvetica",
      style: "normal",
      size: 8.3,
      color: [71, 85, 105],
    });

    doc.text(String(item.quantity || 0), qtyX, rowY + 11);
    doc.text(formatMoney(item.unitPrice), unitPriceX, rowY + 11);

    setText(doc, {
      font: "helvetica",
      style: "bold",
      size: 8.7,
      color: [15, 23, 42],
    });

    doc.text(formatMoney(item.lineTotal), totalX, rowY + 11, {
      align: "right",
    });

    doc.setDrawColor(226, 232, 240);
    doc.line(x, rowY + rowHeight - 4, x + width, rowY + rowHeight - 4);
  });

  let nextY = y + visibleItems.length * rowHeight;

  if (hiddenCount > 0) {
    setText(doc, {
      font: "helvetica",
      style: "italic",
      size: 8,
      color: [100, 116, 139],
    });

    doc.text(
      `+ ${hiddenCount} more item${hiddenCount === 1 ? "" : "s"} summarized to keep this invoice on one page.`,
      x + 10,
      nextY + 10
    );

    nextY += 16;
  }

  return nextY;
}

export function buildInvoicePdf({ invoice = {}, owner = {}, origin = "" } = {}) {
  const customerName =
    invoice.customer ||
    invoice.customerName ||
    invoice.student ||
    invoice.studentName ||
    "Customer";

  const businessName = invoice.businessName || owner.businessName || "InvoiceHub";
  const invoiceNumber = invoice.invoiceNumber || "Pending";
  const invoiceDate = invoice.date || invoice.createdAt || new Date();
  const dueDate = invoice.dueDate || invoice.date || invoice.createdAt || new Date();

  const description =
    invoice.description || invoice.category || invoice.class || "Invoice payment";

  const items = sanitizeInvoiceItems(invoice.items || []);

  const originalAmount = getOriginalInvoiceAmount(invoice);
  const paidAmount = getAmountPaid(invoice);
  const amountDue = getAmountDue(invoice);

  const paymentLink =
    origin && invoice.token
      ? `${origin.replace(/\/$/, "")}/pay/${invoice.token}`
      : "";

  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 38;
  const footerY = pageHeight - 34;
  const contentWidth = pageWidth - margin * 2;

  let y = drawDocumentHeader({
    doc,
    businessName,
    documentTitle: "Invoice",
    margin,
    pageWidth,
    startY: 28,
  });

  const summaryHeight = 92;

  addCard(doc, margin, y, contentWidth, summaryHeight, {
    fill: [248, 250, 252],
    stroke: [226, 232, 240],
    radius: 12,
  });

  setText(doc, {
    font: "helvetica",
    style: "bold",
    size: 8.5,
    color: [71, 85, 105],
  });

  doc.text("AMOUNT DUE", margin + 18, y + 24);

  setText(doc, {
    font: "helvetica",
    style: "bold",
    size: 25,
    color: [15, 23, 42],
  });

  doc.text(formatMoney(amountDue), margin + 18, y + 58);

  setText(doc, {
    font: "helvetica",
    style: "normal",
    size: 8.8,
    color: [71, 85, 105],
  });

  doc.text(`Invoice ${invoiceNumber}`, margin + 18, y + 78);

  doc.text(`Due ${formatDate(dueDate)}`, pageWidth - margin - 18, y + 78, {
    align: "right",
  });

  y += summaryHeight + 16;

  const detailsHeight = 112;

  addCard(doc, margin, y, contentWidth, detailsHeight, {
    fill: [255, 255, 255],
    stroke: [226, 232, 240],
    radius: 12,
  });

  const colGap = 18;
  const colWidth = (contentWidth - 36 - colGap) / 2;
  const leftX = margin + 18;
  const rightX = leftX + colWidth + colGap;

  let leftY = y + 24;
  let rightY = y + 24;

  leftY = addLabelValue(doc, "Invoice No.", invoiceNumber, leftX, leftY, colWidth);
  leftY = addLabelValue(doc, "Invoice Date", formatDate(invoiceDate), leftX, leftY, colWidth);
  leftY = addLabelValue(doc, "Due Date", formatDate(dueDate), leftX, leftY, colWidth);

  rightY = addLabelValue(doc, "Customer", customerName, rightX, rightY, colWidth);
  rightY = addLabelValue(doc, "Phone", invoice.phone || "-", rightX, rightY, colWidth);
  rightY = addLabelValue(doc, "Email", invoice.email || "-", rightX, rightY, colWidth);

  y += detailsHeight + 14;

  const descriptionHeight = 58;

  addCard(doc, margin, y, contentWidth, descriptionHeight, {
    fill: [248, 250, 252],
    stroke: [226, 232, 240],
    radius: 10,
  });

  setText(doc, {
    font: "helvetica",
    style: "bold",
    size: 8.2,
    color: [71, 85, 105],
  });

  doc.text("DESCRIPTION", margin + 14, y + 18);

  setText(doc, {
    font: "helvetica",
    style: "normal",
    size: 9.2,
    color: [15, 23, 42],
  });

  const descriptionLines = splitText(doc, description, contentWidth - 28).slice(0, 2);
  doc.text(descriptionLines, margin + 14, y + 34);

  y += descriptionHeight + 14;

  const amountBreakdownHeight = paidAmount > 0 ? 44 : 0;
  const totalCardHeight = 64;
  const paymentCardHeight = paymentLink ? 68 : 0;
  const noteHeight = 42;

  const bottomReserved =
    amountBreakdownHeight + totalCardHeight + paymentCardHeight + noteHeight + 46;

  const availableForItems = Math.max(84, footerY - y - bottomReserved);

  if (items.length > 0) {
    y = drawItemsTable({
      doc,
      items,
      x: margin,
      y,
      width: contentWidth,
      maxHeight: availableForItems,
    });

    y += 10;
  } else {
    const serviceLineHeight = 54;

    addCard(doc, margin, y, contentWidth, serviceLineHeight, {
      fill: [255, 255, 255],
      stroke: [226, 232, 240],
      radius: 10,
    });

    setText(doc, {
      font: "helvetica",
      style: "bold",
      size: 8.5,
      color: [71, 85, 105],
    });

    doc.text("SERVICE", margin + 14, y + 18);
    doc.text("BALANCE DUE", pageWidth - margin - 14, y + 18, {
      align: "right",
    });

    setText(doc, {
      font: "helvetica",
      style: "normal",
      size: 9.3,
      color: [15, 23, 42],
    });

    doc.text(truncateText(description, 78), margin + 14, y + 37);

    setText(doc, {
      font: "helvetica",
      style: "bold",
      size: 9.5,
      color: [15, 23, 42],
    });

    doc.text(formatMoney(amountDue), pageWidth - margin - 14, y + 37, {
      align: "right",
    });

    y += serviceLineHeight + 12;
  }

  if (paidAmount > 0) {
    addCard(doc, margin, y, contentWidth, amountBreakdownHeight, {
      fill: [255, 255, 255],
      stroke: [226, 232, 240],
      radius: 10,
    });

    setText(doc, {
      font: "helvetica",
      style: "normal",
      size: 8.3,
      color: [71, 85, 105],
    });

    doc.text(`Original invoice: ${formatMoney(originalAmount)}`, margin + 14, y + 18);
    doc.text(`Paid: ${formatMoney(paidAmount)}`, margin + 190, y + 18);

    setText(doc, {
      font: "helvetica",
      style: "bold",
      size: 8.5,
      color: [180, 83, 9],
    });

    doc.text(`Balance: ${formatMoney(amountDue)}`, pageWidth - margin - 14, y + 18, {
      align: "right",
    });

    y += amountBreakdownHeight + 12;
  }

  addCard(doc, margin, y, contentWidth, totalCardHeight, {
    fill: [15, 23, 42],
    stroke: [15, 23, 42],
    radius: 12,
  });

  setText(doc, {
    font: "helvetica",
    style: "bold",
    size: 11,
    color: [255, 255, 255],
  });

  doc.text("Total Balance Due", margin + 18, y + 26);

  setText(doc, {
    font: "helvetica",
    style: "bold",
    size: 20,
    color: [255, 255, 255],
  });

  doc.text(formatMoney(amountDue), pageWidth - margin - 18, y + 30, {
    align: "right",
  });

  setText(doc, {
    font: "helvetica",
    style: "normal",
    size: 8.5,
    color: [203, 213, 225],
  });

  doc.text(`Invoice ${invoiceNumber}`, margin + 18, y + 48);

  y += totalCardHeight + 12;

  if (paymentLink) {
    addCard(doc, margin, y, contentWidth, paymentCardHeight, {
      fill: [240, 249, 255],
      stroke: [186, 230, 253],
      radius: 12,
    });

    setText(doc, {
      font: "helvetica",
      style: "bold",
      size: 8.5,
      color: [3, 105, 161],
    });

    doc.text("PAYMENT LINK", margin + 14, y + 18);

    setText(doc, {
      font: "helvetica",
      style: "normal",
      size: 8.4,
      color: [3, 105, 161],
    });

    const paymentLines = splitText(doc, paymentLink, contentWidth - 28).slice(0, 2);
    doc.text(paymentLines, margin + 14, y + 35);

    y += paymentCardHeight + 12;
  }

  addCard(doc, margin, y, contentWidth, noteHeight, {
    fill: [248, 250, 252],
    stroke: [226, 232, 240],
    radius: 10,
  });

  setText(doc, {
    font: "helvetica",
    style: "normal",
    size: 8.4,
    color: [71, 85, 105],
  });

  doc.text(
    "Please pay the balance due using the payment link or the payment instructions provided by the business.",
    margin + 14,
    y + 24
  );

  drawFooter(doc, {
    margin,
    pageWidth,
    footerY,
  });

  return Buffer.from(doc.output("arraybuffer"));
}

export function buildInvoiceAttachment({
  invoice = {},
  owner = {},
  origin = "",
} = {}) {
  const buffer = buildInvoicePdf({
    invoice,
    owner,
    origin,
  });

  const invoiceNumber = cleanFilePart(
    invoice.invoiceNumber || invoice._id || "invoice"
  );

  return {
    filename: `invoice-${invoiceNumber}.pdf`,
    mimetype: "application/pdf",
    base64: buffer.toString("base64"),
    size: buffer.length,
  };
}