import { jsPDF } from "jspdf";

function formatMoney(amount) {
  return `N${Number(amount || 0).toLocaleString()}`;
}

function formatDate(value = new Date()) {
  const date = value ? new Date(value) : new Date();

  if (Number.isNaN(date.getTime())) {
    return new Date().toLocaleString();
  }

  return date.toLocaleString();
}

function cleanFilePart(value) {
  return String(value || "receipt")
    .replace(/[^a-z0-9_-]+/gi, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

export function buildPaymentReceiptPdf({
  invoice = {},
  owner = {},
  amount,
  paymentReference = "",
} = {}) {
  const paidAmount = amount ?? invoice.paidAmount ?? invoice.amount ?? 0;
  const customerName =
    invoice.customer || invoice.customerName || invoice.student || "Customer";
  const businessName = invoice.businessName || owner.businessName || "InvoiceHub";
  const invoiceNumber = invoice.invoiceNumber || "Pending";
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = 56;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(businessName, margin, y);

  doc.setFontSize(14);
  doc.text("Payment Receipt", pageWidth - margin, y, { align: "right" });
  y += 32;

  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(1);
  doc.line(margin, y, pageWidth - margin, y);
  y += 34;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105);
  doc.text("Receipt generated by InvoiceHub after successful payment.", margin, y);
  y += 32;

  const rows = [
    ["Invoice Number", invoiceNumber],
    ["Customer", customerName],
    ["Amount Paid", formatMoney(paidAmount)],
    ["Payment Date", formatDate(invoice.paidAt || invoice.updatedAt || new Date())],
    ["Payment Provider", invoice.paymentProvider || "Payment"],
    [
      "Payment Reference",
      paymentReference ||
        invoice.paymentReference ||
        invoice.pendingPaymentReference ||
        invoice.transactionReference ||
        "-",
    ],
    [
      "Description",
      invoice.description || invoice.category || invoice.class || "Invoice payment",
    ],
  ];

  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text(label, margin, y);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    const wrapped = doc.splitTextToSize(String(value || "-"), pageWidth - margin * 2 - 160);
    doc.text(wrapped, margin + 160, y);
    y += Math.max(24, wrapped.length * 15);
  });

  y += 18;
  doc.setFillColor(236, 253, 245);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 54, 8, 8, "F");
  doc.setTextColor(6, 95, 70);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Payment confirmed. Thank you.", margin + 18, y + 32);

  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    "This receipt confirms the payment recorded on InvoiceHub.",
    margin,
    doc.internal.pageSize.getHeight() - 40
  );

  return Buffer.from(doc.output("arraybuffer"));
}

export function buildPaymentReceiptAttachment({
  invoice = {},
  owner = {},
  amount,
  paymentReference = "",
} = {}) {
  const buffer = buildPaymentReceiptPdf({
    invoice,
    owner,
    amount,
    paymentReference,
  });
  const invoiceNumber = cleanFilePart(invoice.invoiceNumber || invoice._id || "receipt");

  return {
    filename: `payment-receipt-${invoiceNumber}.pdf`,
    mimetype: "application/pdf",
    base64: buffer.toString("base64"),
    size: buffer.length,
  };
}
