import mongoose from "mongoose";

const InvoiceSchema = new mongoose.Schema({
  invoiceNumber: String,
  customer: String,
  customerName: String,
  category: String,
  description: String,
  items: [
    {
      id: String,
      description: String,
      quantity: Number,
      unitPrice: Number,
      lineTotal: Number,
    },
  ],
  subtotal: Number,
  phone: String,
  email: String,
  token: String,
  amount: Number,
  status: String,
  date: Date,
  businessName: String,
  customerToken: String,
  paymentReference: String,
  paymentProvider: String,
  paymentVerificationMethod: String,
  paymentStatus: String,
  paymentConfirmedAt: Date,
  paidAt: Date,
  paidAmount: Number,
  balanceDue: Number,
  customerNotificationStatus: String,
  customerNotificationQueuedAt: Date,
  customerNotificationPreparedAt: Date,
  lastReminderSentAt: Date,
  lastReminderProvider: String,
  lastReminderOutcome: String,
  reminderSendCount: Number,
  pendingPaymentReference: String,
  pendingPaymentAmount: Number,
  pendingPaymentProvider: String,
  pendingPaymentCreatedAt: Date,
});

export default mongoose.models.Invoice || mongoose.model("Invoice", InvoiceSchema);
